### ISSUE TITLE
Are you planing in supporting gpx files for coordinates? 

### ISSUE THREAD

**Issue by otmezger** [marchyman/GeoTag#11]
I was wondering if this project will support gpx files at some point in time. I could not find this functionality in the current version. 
thanks

**Comment by marchyman** [comment]
Unlikely.  ExifTool can match image files to GPX files by timestamp.  Locations can be then be verified and tweaked if necessary in GeoTag. 

See [GeoTagging with ExifTool](https://sno.phy.queensu.ca/~phil/exiftool/geotag.html) for examples.
