### ISSUE TITLE
Modify Date/Time won't work

### ISSUE THREAD

**Issue by lucaspellucci** [marchyman/GeoTag#12]
Hi, thanks for this App! it's been great help for me to organize my pictures, I was really excited to use the Option to "Modify Date/Time" however when I double-click the column nothing happens, if I right click the photo and click "Modify Date/Time", the window opens for less then a second and closes. If I select from the Menu, the window then open, however whatever I set there as New date is not saved.

My Os: 10.12.6

**Comment by marchyman** [comment]
I just noticed this issue -- sorry for the delay (and happy new year).

Was the image jpeg or some other type?  Are you using a mouse or a track pad?  I don't know that the answers to those questions will lead me toward resolution of the issue, but it is a starting point.

**Comment by lucaspellucci** [comment]
Hi @marchyman , happy new year! The image is jpeg and I am using a mouse. The funny thing is that it appears to work for some files but not for others. I can send you an example of a file that doesn't work if you want to. Thanks a lot!

**Comment by lucaspellucci** [comment]
Ok, I think I've found the issue, if I double click the image name in the list and set the date it works, If I single click to select the image, right-click and click "Modify Date/Time" it doesn't work.

**Comment by marchyman** [comment]
Thanks for the extra information.  I'll try to dig up an older version of the OS to hopefully reproduce the issue as  I'm not seeing that behavior on macos 10.14.2.

**Comment by marchyman** [comment]
It's been many years and no one else has reported a similar issue.  I'm going to close this.
