### ISSUE TITLE
Incorrect sort order after opening files

### ISSUE THREAD

**Issue by woutgg** [marchyman/GeoTag#16]
When opening a selection of photos, they are added to the list in a seemingly random order.
Clicking on a column header sorts the list as expected.

The issue also occurs after a sort order has explicitly been set (by clicking on a column header), as can be observed by clearing the list and opening a new selection of images.

**Comment by marchyman** [comment]
On Feb 7, 2020, at 12:01 PM, Wout R. <notifications@github.com> wrote:
> 
> When opening a selection of photos, they are added to the list in a seemingly random order.

Yes.  The order is that given by macOS in the open panel.  For directories I believe it is the order of the files in the directory -- again, supplied by macOS.  GeoTag makes no attempt to order the images unless requested by clicking on a column header.

> The issue also occurs after a sort order has explicitly been set (by clicking on a column header), as can be observed by clearing the list and opening a new selection of images.

Perhaps that should change. When the user selects a sort order it is reasonable to believe that the sort order be maintained.   And if GeoTag does that it should also probably remember the requested sort order for future file opens, even on subsequent runs of the program.   I’ll add that to the list of requested changes.   Thank You.

Marc

**Comment by marchyman** [comment]
Fix is in github.  It will be part of the next release.   I don't know when that will be.

**Comment by woutgg** [comment]
Great, thank you for the changes!

I would expect though, that a 'sane default' would be applied as well, as the OS-provided order is not meaningful in this context. I think it's also common/conventional to default to sorting ascending by name in cases like these.

That  being said, maintaining the actively set order is the most important aspect, so I'm happy. :)
