### ISSUE TITLE
Feature request. Zoom

### ISSUE THREAD

**Issue by anvme** [marchyman/GeoTag#19]
Can u add zoom for images?

**Comment by marchyman** [comment]
I'll look into it.  No promises.

**Comment by marchyman** [comment]
It's a performance issue.   To zoom I need the entire image.   Keeping the entire image uses lots of space and it takes longer to render the image into a small space.  For those reason I create a smaller thumbnail (512x512) when needed and only keep the thumbnail around.  And thumbnail generation is done in the background.
