### ISSUE TITLE
window sizing issues

### ISSUE THREAD

**Issue by sweetppro** [marchyman/GeoTag#2]
I only have a MacBook Air, the default window height fills the screen and can't be made smaller. Also when I move the window, it "jumps" back to the top of the screen

**Comment by marchyman** [comment]
I assume you've the 11" air?   I have a 2010 version of the 13" model and don't see that.  What is the resolution of your air? 1366 by 768?   Looks like the minimum window size is 1024x768.   I'll change it to 800x600 to fit on the air.

**Comment by sweetppro** [comment]
yeah I have the 11"
  Resolution:	1366 x 768

:)

**Comment by marchyman** [comment]
Thank you.   http://www.snafu.org/GeoTag/GeoTag-3.4.4.dmg has the same fix for others with the same issue.
