### ISSUE TITLE
Feature request. Show in finder

### ISSUE THREAD

**Issue by anvme** [marchyman/GeoTag#20]
Can u add in the right-click menu point - show in finder?

**Comment by marchyman** [comment]
I like this idea. 

And I see a bug.  Holding the mouse over an entry in the table is supposed to display a tool tip containing the full path to the image.  That isn't happening any more.

**Comment by anvme** [comment]
>display a tool tip containing the full path to the image.
That's not a problem ;)

**Comment by marchyman** [comment]
The tool tip only shows up when hovering over the image name, not the timestamp or location.  I'd forgotten that.

Added Show in Finder to the context menu.  It will be in the next release.
