### ISSUE TITLE
Feature request. Saved list of location

### ISSUE THREAD

**Issue by anvme** [marchyman/GeoTag#21]
Can you add a saved list of locations?
After the longitude, it will be cool. 
With available paste by cmd + V or from saved list.

**Comment by marchyman** [comment]
I use a previously tagged image.  Or I search for the location.   The last 10 search locations are already saved.

**Comment by anvme** [comment]
> I use a previously tagged image. Or I search for the location. The last 10 search locations are already saved.

=) Only hard locations with google
I don't search, because it is not set the point, what I need.

**Comment by anvme** [comment]
In search, cool! search input, maybe it will use saved list of locations in settings?
