### ISSUE TITLE
Ignore update error and highlight rows 

### ISSUE THREAD

**Issue by anvme** [marchyman/GeoTag#22]
It is possible to ignore update errors and go to the next image? Also, it will be useful to highlight the problem images. Or set red tag /!\ before the name.

**Comment by marchyman** [comment]
A backup thread is fired up each image when you request a save from the menu or cmd-s.   A failure on one image does not stop the updating of others.   The error message isn't shown until all of the backup threads have completed to indicate if one or more of the images failed to save.  

Marking the images that did not back-up correctly is a good idea.  I will do that.

**Comment by marchyman** [comment]
Entries for images with backups that fail will change to orange.
Entries for images were the update failed will change to red.
These changes are have been committed and will be part of the next release.

<img width="615" alt="Screen Shot 2020-03-22 at 4 15 57 PM" src="https://user-images.githubusercontent.com/784627/77264922-9f138580-6c58-11ea-8d82-9ea94758d0b5.png">
