### ISSUE TITLE
Inactive images

### ISSUE THREAD

**Issue by anvme** [marchyman/GeoTag#25]
<img width="710" alt="Screen Shot 2020-03-22 at 9 48 49 PM" src="https://user-images.githubusercontent.com/56738034/77257685-eb75ba00-6c86-11ea-9404-e1e7f2885c76.png">
They are inactive. I can't edit them.
Example image - https://www.swisstransfer.com/d/841ebad4-eac9-440e-ab94-927b39b78479

**Comment by marchyman** [comment]
And yet it is editable on my system.

<img width="626" alt="Screen Shot 2020-03-22 at 11 58 43 AM" src="https://user-images.githubusercontent.com/784627/77257915-842f1a00-6c34-11ea-8a8e-0492d09894fd.png">

Something else to look at.

**Comment by anvme** [comment]
I try different times =(
What can be wrong? No external drive. Good free space..

**Comment by marchyman** [comment]
I'm closing this not because an issue has been fixed, but because I can't duplicate it and there have been no other similar complaints.  I suspect it is something unique to the reporter's environment, but I don't know what.   Sorry.
