### ISSUE TITLE
Date/Time 

### ISSUE THREAD

**Issue by anvme** [marchyman/GeoTag#26]
Images have different types of date/time.
Can you add them to the list of available to edit?
**Creation, modify**

<img width="322" alt="Screen Shot 2020-03-23 at 5 14 51 PM" src="https://user-images.githubusercontent.com/56738034/77325708-d00fbb00-6d29-11ea-8298-d5bd66af7f69.png">

**Comment by marchyman** [comment]
Created, Modified, and Last opened are file system timestamps; they are not part of image metadata.  The image specific timestamps are ModifyDate, DateTimeOriginal (when the image was digitized) and CreateDate (when the digitized image was written).  The last two timestamps are usually the same.

GeoTag used to update ALL dates all the time.   That changed after complaints were received from users.  Currently it updates DateTimeOriginal and CreateDate and then only when changed.   I believe this is the best solution for most people.

If you want the file dates to match the image metadata dates you can use exiftool.   The command is

`exiftool "-FileCreateDate<CreateDate" "-FileModifyDate<CreateDate" image-name`

using . in place of image name will change all images in the current folder.
