### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by KovalevArtem** [marchyman/GeoTag#27]
It is sad that the application is only in English - I propose to translate.
I am ready to help in the translation into **Russian**.
(For example, you can use **Weblate**, or any other service. It is completely free for open source projects.)

![image](https://user-images.githubusercontent.com/36500228/98449379-2b20e180-2144-11eb-8870-57606b640a77.png)

**Comment by marchyman** [comment]
I'll certainly look at pull requests that add other languages.   Many, many versions ago GeoTag supported Spanish.   The program changed much since then.  I had to remove support as it was no longer accurate.
