### ISSUE TITLE
Introduce Fujifilm compressed RAW support

### ISSUE THREAD

**Issue by enRGi** [marchyman/GeoTag#28]
Regular Fujifilm camera RAWs are working fine. Compressed ones however are not working.

**Comment by marchyman** [comment]
I don't know if this is a "apple doesn't support that, yet" issue or a "GeoTag is not doing something right" issue.  Does Finder and quick look show the compressed images?  If so it is likely a GeoTag error.  Can you send me one of the images for me to test?

**Comment by enRGi** [comment]
Yes, you're right. I also do not have a preview when seeing those in Finder. Here I have an image in that format for you:
[DSCF6542.RAF.zip](https://github.com/marchyman/GeoTag/files/8208267/DSCF6542.RAF.zip)

**Comment by marchyman** [comment]
Thanks.  I also tried looking at the image using Preview.app -- it can't read the format.  I'll submit a bug/feature request to Apple requesting that it support the format.  Both Adobe Lightroom Classic and Capture One process the image correctly.

**Comment by marchyman** [comment]
I'm going to close this as there is nothing GeoTag can do.   It is up to Apple to fix this.

**Comment by alexwhittemore** [comment]
That's exactly what I'm seeing, but turns out it's because I was on Sequoia 15.7. Reading some chatter, the macOS update to support compressed RAF is in Tahoe. Now that I've just updated to 26.3, both finder and GeoTag support my raws perfectly. Thanks for leading me to that!
