### ISSUE TITLE
Allow pasting Latitude/Longitude coordinates in comma notation

### ISSUE THREAD

**Issue by enRGi** [marchyman/GeoTag#29]
When entering the location coordinates manually, the fields for Latitude/Longitude are separated and it is not possible to simply paste it in the form <latitude>,<longitude>. This would be more convenient.

**Comment by marchyman** [comment]
Lat and Lon can be pasted using a vertical bar as a separator, i.e.  "38.295534839853644 | -122.70576473325491".  That format is also used when you copy a lat/lon from one entry in the table to past into another.

**Comment by enRGi** [comment]
ok, good to know. However, this may still be convenient, as this is the format you get when taking the coordinates from Google Maps:
<img width="251" alt="Bildschirmfoto 2022-03-08 um 18 11 57" src="https://user-images.githubusercontent.com/8393975/157289742-5dc691ed-96c5-48c7-979c-d3259083612a.png">

**Comment by marchyman** [comment]
I see.  Originally I used a space, but had to change when I started supporting "deg min sec" format in addition to fractions of a degree.   I didn't use comma because that is the decimal symbol in some locales.  I wonder what Google Maps returns in such places?

**Comment by enRGi** [comment]
Ah, yes maybe... Maybe this can be tested by setting the browser to different locales - in my case it is 'german'.
