### ISSUE TITLE
“Suppress“ JPG when DNG exists - why? Considered harmful.

### ISSUE THREAD

**Issue by joergRossdeutscher** [marchyman/GeoTag#33]
Hello, I've upgraded to the latest version of GeoTag and immediately had to downgrade again. There is a new feature to “suppress“ working on a JPG file when a DNG with the same name exists. I believed this to be a bug, until I found out it's intentionally.

I don't see a use or reason in this? I kindly ask to make this configurable.

I am using an Android Phone with multiple camera apps. Everyone of those apps lets me decide which format I want to use, JPG or DNG or BOTH. I am using “BOTH“ everywhere, because for daily quick usage the JPGs are more handy, while having the DNGs is nice in some rare cases, for when I take a photo Elvis entering an UFO I'll happily sell the DNG to the newspaper, but usually I don't work with DNGs.

Additionally: Some Android Cameras do NOT use the same filename here. They use the “current“ timestamp for both files individually, so maybe one has 12000**0**.jpg and 12000**1**.dng , I have that alot in my collection.

Long story said short: This creates a mess for me, because I intentionally want both files, the JPG is even the usual “master“, plus additionally the mapping per filename is totally not reliable.

I think someone had the idea people would take photos as DNG only and then “develop“ them as JPGs later, but this seems not to be a realistic case. Nobody will i.e. attach a DNG to his WhatsApp message, so JPG is the daily driver here.

(It's not a real workaround to edit JPG and DNG separately, because this would make it painful to make the identical correction on both files)

Would be great if you could add a config option here.

**Comment by joergRossdeutscher** [comment]
OK, I still don't get what might be the advantage of that feature, for me it just breaks normal workflows.

However, maybe others see that as a problem also, so, this is what I do to work around it:

1. Get a tool like “NameChanger.app“ from MRR Software
2. rename all dng files with a schema like “Replace: .dng with _.dng“, now your DNG files have an additional "_" at ther end of the name
3. Work with GeoTag like before
4. rename all dng files the other way around, from _.dng to .dng

…and please, I would really like a config checkbox for this. Why would I hide half of my photos from tagging them?

**Comment by marchyman** [comment]
Changing the way it current works is on the to do list.  Adding a check box is one of the possible changes.

An issue: if each representation of an image (dng and jpg) are treated separately then each can have a different location. In that situation at least one (and maybe both) images are incorrectly located.  Switching between two versions of the same image and having the map jump around drives those with a touch of OCD crazy.

My personal solution is to never shoot jpg.  I know that doesn’t work for everyone.  In your "attach to a WhatsApp message" scenario I'd crop and edit the DNG image to taste, export the edited image as a jpeg in the appropriate size, then attach that image.  No, it's not quick. And not something I do very often.  An image attached to a message is most likely to be a quick snapshots taken with my phone.

Anyway, next release (don't know when that will be, yet) will have changes in the way DNG/JPG images are handled; hopefully changes that meet your need.

**Comment by joergRossdeutscher** [comment]
Thanks a lot! That would help so much!

**Comment by marchyman** [comment]
The branch GeoTag5 contains what will be the next release when I finish testing and updating the documentation.   It has a user option to ignore the jpeg part of raw/jpeg pairs.  When disabled the file is listed, but not selectable or editable.  I hope that meets your needs.
