### ISSUE TITLE
Add support for altitude/elevation?

### ISSUE THREAD

**Issue by freerobby** [marchyman/GeoTag#34]
Would you consider adding support for altitude/elevation?

The exiftool tag would be GPSAltidude.

In GPX files these data are typically included in the `<ele>` tag, e.g.:
```
			<trkpt lat="..." lon="...">
				<ele>[[altitude in meters]]</ele>
			</trkpt>
```

**Comment by marchyman** [comment]
Adding elevations when matching a track log is doable as the data is available.  Elevation from clicking on the map is something else.  GeoTag is somewhat built around a 2D location.   Clicking on a map gives me an X/Y window coordinate which I can convert to a latitude and longitude.   I'm not sure what it would take to getting an elevation from a lat/lon.  Last time I looked (many, many years ago) I'd need to either include largish DEM (digital elevation model) files or require network access.  Neither solution met my needs at the time.

**Comment by freerobby** [comment]
@marchyman Thanks for the quick response and for the consideration here.

Yeah, I had envisioned this for applying GPX files, not for deducing altitude from a terrain map. I typically record a GPX on my phone and then use GeoTag to apply it to all the photos I took during that session.

**Comment by marchyman** [comment]
The branch GeoTag5 contains what will be the next release. It includes elevation when assigning locations from track logs.  GeoTag5 will be released when I finish testing and updating the documentation.

**Comment by freerobby** [comment]
🙏
