### ISSUE TITLE
Multiple GPS pin positions in map

### ISSUE THREAD

**Issue by togarha** [marchyman/GeoTag#35]
I would like to see 3 different pins on the map (when available):
- Green: Image current position
- Blue: Position from GPS track
- Red: The "future" position when applying changes

With 3 buttons, we might select which of the 3 we want to set to each image...

By default, if there is a position in the image, the red pin will be at the same location as the green one. If clicking on the "from track" the red one will be at the same position as the blue one. If clicking on the map, or searching, the red one will be in a different position than the green and blue ones...

I would like to contribute to the project because I want to add more things I have in mind, but I don't have any experience with Swift, even though I have experience with other languages. I'm thinking to learn about it, but still looking for a good tutorial, and time to experiment...

**Comment by marchyman** [comment]
Interesting idea.  The GeoTag Image model has the information needed to show location since last saved (which is often no location at all) and the current location.  There is currently no way to show a proposed changed or a "this is where the image might be if we match timestamps with some loaded track log".

The initial idea for the program -- assigning a location to images that have none -- didn't include anything like comparing potential positions.

**Comment by marchyman** [comment]
As for contributing to the project -- feel free to jump in.  But... be aware that I am in the very slow process of re-writing the app to use SwiftUI.  It's slow as SwiftUI doesn't yet let me do everything that I can do using the older interface builder.   Do not expect to see GeoTag 5 any time soon.

Also, any new version will likely require the latest macOS.  I expect the current version to live as long as people are using older macOS releases.

Check out [Hacking With Swift](https://www.hackingwithswift.com) for Swift instruction.

**Comment by togarha** [comment]
> Interesting idea. The GeoTag Image model has the information needed to show location since last saved (which is often no location at all) and the current location. There is currently no way to show a proposed changed or a "this is where the image might be if we match timestamps with some loaded track log".
> 
> The initial idea for the program -- assigning a location to images that have none -- didn't include anything like comparing potential positions.

But is it possible to implement, or make sense to you to add to the program even though there isn't any current way to show it?

**Comment by togarha** [comment]
> As for contributing to the project -- feel free to jump in. But... be aware that I am in the very slow process of re-writing the app to use SwiftUI. It's slow as SwiftUI doesn't yet let me do everything that I can do using the older interface builder. Do not expect to see GeoTag 5 any time soon.
> 
> Also, any new version will likely require the latest macOS. I expect the current version to live as long as people are using older macOS releases.
> 
> Check out [Hacking With Swift](https://www.hackingwithswift.com) for Swift instruction.

I have no info about Swift, so even less about SwiftUI :D and I use an old MacOS version, even though I have to update it, there are too many things I want to do before that...

Thanks for the Swift link, I'll try to take a look and prepare all the environment, at least to be able to look at the GeoTag code, trying to contribute to the project...

**Comment by marchyman** [comment]
The (mostly) SwiftUI version is in the branch GeoTag5.  It will be the next release when I finish testing and documentation.

**Comment by togarha** [comment]
I´ve just reviewed the requirements for GeoTag5 and as it needs Ventura OS, it won't be compatible with my laptop, it only supports up to Monterey, it's a pity, but I'll check if it's worth for me to fork the repo and continue with the legacy version.
Thanks for your previous comments and advice...

**Comment by marchyman** [comment]
The latest 4.x version is on a branch labeled GeoTag4 -- which I see I didn't  push to GitHub.  Fixed.  It contains a commit or two that isn't in the 4.15 release.  I was going to add support for Elevation/Altitude in the 4.x branch but then started work on version 5.

**Comment by togarha** [comment]
I'll take a look, thanks

**Comment by marchyman** [comment]
Slight improvements made in GeoTag 5.2.  The option to toggle how many pins are shown in in the View menu.
