### ISSUE TITLE
Click on the map doesn't always respond

### ISSUE THREAD

**Issue by earlmckay** [marchyman/GeoTag#38]
On the Mac (13.4.1) and GeoTag 5.1 (and earlier) it takes countless clicks (over 30) until a marker is placed on the map.

**Comment by mhschaap** [comment]
I experience the same with 5.1 and latest Sonoma

**Comment by mhschaap** [comment]
Hello @marchyman. Many thanks for your message and your great work. I did a test with the same photos I processed last year. It works great now. When I click a file, the pin hovers on the map over the track, and the correct photo is shown. Thanks again!
