### ISSUE TITLE
Geotag 5 extremely slow

### ISSUE THREAD

**Issue by Thueringer-2** [marchyman/GeoTag#39]
System: iMac retina 27" 2020, Intel Core i5, 32GB RAM
OS: v14 "Sonora"
Geotag 5.1 (1093)

Steps to reproduce:

Drop folder with 600 files to the folder view.
Click on one image
Problem: It takes up to 15 seconds until the image is selected, the coordinate is shown and the preview is shown.

The same happens if 
- coordinates are to be copied from one file to others: Between mouse clicks about 5 seconds are required.
- coordinates are to be saved: It takes about 5 seconds to save the coordinates for each file (coordinate colour turns from green to black)

**Comment by marchyman** [comment]
Alas, this is a known issue.  Instrumenting the program and then testing shows the slowdown to be inside Apple's SwiftUI code.  As expected the larger the number of images in the table the longer the delay.  I've reported the issue to Apple.

Supposedly performance is improved if I update to features that are only supported in Sonoma and later.   I've done some work in that direction but did not find this particular issue to get much better.  I'm still looking at ways to improve performance.

**Comment by Thueringer-2** [comment]
Thank you for assessing the issue! 
Will use less files for now and check for future Geotag updates.
