### ISSUE TITLE
Add information about this being available as a Cask

### ISSUE THREAD

**Issue by thibmaek** [marchyman/GeoTag#4]
I added a Cask for this so people can install it trough that with `brew cask install geotag`

Ref. PR: https://github.com/caskroom/homebrew-cask/pull/13137
Ref. Code: https://github.com/caskroom/homebrew-cask/pull/13137/files#diff-4cd5f15a7c185c30587a21e3d4360c36

**Comment by marchyman** [comment]
Thank you!  I'll update the readme with that info.

**Comment by marchyman** [comment]
README updated
