### ISSUE TITLE
Paste keyboard shortcut doesn't work in search bar.

### ISSUE THREAD

**Issue by mxcolin** [marchyman/GeoTag#42]
I frequently copy and paste coordinates into the search bar, but the keyboard shortcuts don't work (Command+V), so I need to right-click and select paste. not a show-stopper but makes my workflow very frustrating.

**Comment by marchyman** [comment]
Noted.  The same issue was present when entering latitude and longitude values.  I hope to resolve this issue with the next release.  I'll keep this issue open until I know I have a working fix.

**Comment by marchyman** [comment]
Fixed in version 5.2
