### ISSUE TITLE
Preview Image Quality Very Poor

### ISSUE THREAD

**Issue by mxcolin** [marchyman/GeoTag#43]
The preview image pane is very blurry when compared with viewing the image on the OS, or another image viewing application. As an example, I've attached an image showing the GeoTag preview vs. viewing the image on the OS preview.

<img width="1602" alt="Screenshot 2023-12-13 at 8 22 04 AM" src="https://github.com/marchyman/GeoTag/assets/19899400/d55a0f1c-b89f-42d4-a68c-8efa1fc8be00">

You can see that the image on the left (from MacOS preview) is significantly clearer than the Image Preview Pane in GeoTag. The images are so blurry that I often have to open the image in another app to get a clear view of it.

**Comment by marchyman** [comment]
Yes.   The preview is a thumbnail limited to fit in a box 512x512 pixels wide.  This is done to minimize memory use.  It also happens to be about the size of the preview window the way I use GeoTag.  It would be blurry or pixelated when the image pane is extended to larger sized, i.e. GeoTag is full screen.

The next version on GeoTag will raise the thumbnail size to 1024x1024. Perhaps that will address your complaint.

**Comment by mxcolin** [comment]
Yeah that would help for sure, I use it with the preview at at least 900x900
