### ISSUE TITLE
App crashes when saving files

### ISSUE THREAD

**Issue by lyonacre** [marchyman/GeoTag#44]
Just upgraded to Sonoma 14.2.1 and now the app terminates whenever I save files without applying changes

**Comment by marchyman** [comment]
When you try to save the app crashes before any image metadata is updated.  Do I have that correct?

I've not been able to reproduce that problem.  Can you tell me more?  Writing to local disk?  External Disk?  NAS? Using backups?  What kind of image file.

**Comment by marchyman** [comment]
Waiting for feedback?  Does the issue still occur with the just released version 5.2?

**Comment by lyonacre** [comment]
Sorry for not getting back to you. Deleted downloaded and installed latest version. And all working. Problem started after sonoma upgrade. Thanks for getting back to meSent from my iPhoneRegards ***@***.*** 9 Mar 2024, at 18:52, Marco S Hyman ***@***.***> wrote:﻿
Waiting for feedback?  Does the issue still occur with the just released version 5.2?
