### ISSUE TITLE
Feature Request: Apple Maps Pane Zoom In/Out (+/-) Functionality

### ISSUE THREAD

**Issue by ebbhead1991** [marchyman/GeoTag#46]
Since the switch to Apple Maps, the functionality to zoom in and out on the map is limited to pinching/un-pinching… or for those without trackpad/touch input functionality, double-clicking/option+double-clicking.

For the latter method, it's easy to not click fast enough to register a double-click, and drop a pin where it is not expected.

Could the +/- buttons be added to the Apple Maps pane for ease of use, such as in this screenshot?

![Screenshot 2024-03-14 at 9 00 49 AM](https://github.com/marchyman/GeoTag/assets/84095074/6a2de0fe-3a8a-4838-8eff-8da3b5b52b00)

Thank you so much for a wonderfully helpful tool!

**Comment by marchyman** [comment]
Yes, that can be done.  It will be part of the next release and is already checked in to the newmaps branch.
