### ISSUE TITLE
Geotag 5.3  Multiple Images

### ISSUE THREAD

**Issue by kmpott** [marchyman/GeoTag#50]
When selecting multiple images , then selecting location on map. Only GPS co-ordinates are applied to first image.

**Comment by marchyman** [comment]
Noted.  A possible workaround until this is fixed is after clicking on the map copy (cmd-C) and paste (cmd-V) to replicate the change to all selected images.

**Comment by marchyman** [comment]
I'm closing this as the fix has been committed and will be included in the next release.   Thanks for the report.
