### ISSUE TITLE
Add a method to create a pin from center of map

### ISSUE THREAD

**Issue by elmimmo** [marchyman/GeoTag#53]
Please add a menu or button to create a pin in the middle of the Map so that one can blindly tag exactly the same coordinates from whatever location the Map’s search box result produced.

Having to manually click on the map to create a pin results in subtly different coordinates on each press, as one cannot do so consistently.

**Comment by marchyman** [comment]
That fix has already been commited to the "fixes" branch and will be in the next release.  See <https://github.com/marchyman/GeoTag/issues/49>
