### ISSUE TITLE
OFFSET when click map to set location and double click to zoom in && track rendering issue

### ISSUE THREAD

**Issue by chemharuka** [marchyman/GeoTag#56]
Version 5.3.1    14.1.2 (23B92)
1.1 when I click the map to set location:
<img width="542" alt="image" src="https://github.com/marchyman/GeoTag/assets/29047471/60777a54-29b3-4161-b79c-5ed389541ee0">
1.2 wrong location added:
<img width="538" alt="image" src="https://github.com/marchyman/GeoTag/assets/29047471/bd83dc63-c865-4026-aaeb-3b78c9133436">
1.3 when double click the map to zoom in, the scaling origin is also offset
1.4 the offset is related to the map UI height
1.5 please check`mapProxy.convert(position, from: .local)` in` MapView.swift `

BTW
<img width="540" alt="image" src="https://github.com/marchyman/GeoTag/assets/29047471/498cebc3-d738-4ab6-b11b-52943d7f35c1">
new version renders the track in a strange way

**Comment by chemharuka** [comment]
BTW2: I suggest attaching the dmg file to the GitHub release. **Rolling back** to the old version requires me to download the Xcode and compile it. 
BTW3: Compile it require `git init` and `git commit` to meet some requirement in scripts.

**Comment by marchyman** [comment]
See the note on the GeoTag home page.  I’ll repeat it here:

There is a map pin location issue when running on early versions of macOS Sonoma. If you see a pin placed above the point you clicked/tapped you are seeing this bug. Apple fixed the issue in version 14.4 (or perhaps it was 14.4.1). It is not a problem in the current version of Sonoma.

**Comment by chemharuka** [comment]
> See the note on the GeoTag home page. I’ll repeat it here:
> 
> There is a map pin location issue when running on early versions of macOS Sonoma. If you see a pin placed above the point you clicked/tapped you are seeing this bug. Apple fixed the issue in version 14.4 (or perhaps it was 14.4.1). It is not a problem in the current version of Sonoma.

Well, please update readme on GitHub. I guess that's on homepage of your website so I missed it perfectly

**Comment by marchyman** [comment]
Good advice.  I should have done that earlier.  I have added a note to the README.

Thanks.
